# Generated by Django 5.0.7 on 2025-02-01 07:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Enter the FAQ question in English', verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(help_text='Provide the detailed answer', verbose_name='Answer')),
                ('question_hi', models.TextField(blank=True, null=True, verbose_name='Question (Hindi)')),
                ('question_bn', models.TextField(blank=True, null=True, verbose_name='Question (Bengali)')),
            ],
        ),
    ]
