version: "3.9"

services:
  web:
    build: .
    command: gunicorn faq_management.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: faq_db
      POSTGRES_USER: faq_user
      POSTGRES_PASSWORD: faq_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7

volumes:
  postgres_data:
